### ISSUE TITLE
Cannot install or update plugin anymore 

### ISSUE THREAD

**Issue by haffla** [twilio/flex-plugin-library-chat-transfer#64]
Hi. All of the sudden the "TaskRouter Chat Transfer Workflow SID" field is a select, but it's empty. I swear that yesterday it was a normal text field. Any idea?

![Screenshot 2023-12-06 at 18 19 38](https://github.com/twilio/flex-plugin-library-chat-transfer/assets/2844304/9ca1847f-f03d-4ae1-aefc-668f1b7b5063)

**Comment by shyamasish-twilio** [comment]
@haffla , We have released a new patch for plugin library,
This should have been fixed now.
Can you please check once and confirm?

**Comment by haffla** [comment]
@shyamasish-twilio thank you! It's working now 🥇
